version: '3.9'

services:
  simulatecredit-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: simulatecredit-api
    ports:
      - "5000:80"
      - "5001:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - MongoDb__ConnectionString=mongodb://simulatecredit-mongo:27017
      - MongoDb__Database=SimulateCreditDb
      - MongoDb__Collection=simulationscredits
      - RabbitMq__Host=simulatecredit-rabbitmq
      - RabbitMq__Port=5672
    depends_on:
      - mongodb
      - rabbitmq

  mongodb:
    image: mongo
    container_name: simulatecredit-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  rabbitmq:
    image: rabbitmq:3-management
    container_name: simulatecredit-rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

volumes:
  mongo-data:
  